/**
 * Generated by orval v7.20.0 🍺
 * Do not edit manually.
 * Tax API
 * RESTful API for managing tax records.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import * as axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

export type TaxMetadata = { [key: string]: unknown };

export interface Tax {
  id: number;
  tax_year: number;
  jurisdiction: string;
  filing_status: string;
  income: number;
  deductions: number;
  taxable_income: number;
  tax_amount: number;
  currency: string;
  status: string;
  due_date?: string;
  /** @nullable */
  paid_at?: string | null;
  /** @nullable */
  notes?: string | null;
  metadata: TaxMetadata;
  created_at: string;
  updated_at: string;
}

export type TaxInputMetadata = { [key: string]: unknown };

export interface TaxInput {
  tax_year: number;
  jurisdiction: string;
  filing_status: string;
  income: number;
  deductions: number;
  taxable_income: number;
  tax_amount: number;
  currency: string;
  status: string;
  due_date?: string;
  /** @nullable */
  paid_at?: string | null;
  /** @nullable */
  notes?: string | null;
  metadata?: TaxInputMetadata;
}

export interface Error {
  error: string;
  message: string;
}

export type ListTaxesParams = {
  status?: string;
  tax_year?: number;
  jurisdiction?: string;
  limit?: number;
  offset?: number;
};

/**
 * @summary List taxes
 */
export const listTaxes = (
  params?: ListTaxesParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.get('/api/v1/taxes', {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getListTaxesQueryKey = (params?: ListTaxesParams) => {
  return ['/api/v1/taxes', ...(params ? [params] : [])] as const;
};

export const getListTaxesQueryOptions = <
  TData = Awaited<ReturnType<typeof listTaxes>>,
  TError = AxiosError<unknown>,
>(
  params?: ListTaxesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTaxes>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTaxesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTaxes>>> = ({ signal }) =>
    listTaxes(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTaxes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListTaxesQueryResult = NonNullable<Awaited<ReturnType<typeof listTaxes>>>;
export type ListTaxesQueryError = AxiosError<unknown>;

export function useListTaxes<
  TData = Awaited<ReturnType<typeof listTaxes>>,
  TError = AxiosError<unknown>,
>(
  params: undefined | ListTaxesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTaxes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTaxes>>,
          TError,
          Awaited<ReturnType<typeof listTaxes>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTaxes<
  TData = Awaited<ReturnType<typeof listTaxes>>,
  TError = AxiosError<unknown>,
>(
  params?: ListTaxesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTaxes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTaxes>>,
          TError,
          Awaited<ReturnType<typeof listTaxes>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListTaxes<
  TData = Awaited<ReturnType<typeof listTaxes>>,
  TError = AxiosError<unknown>,
>(
  params?: ListTaxesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTaxes>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List taxes
 */

export function useListTaxes<
  TData = Awaited<ReturnType<typeof listTaxes>>,
  TError = AxiosError<unknown>,
>(
  params?: ListTaxesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTaxes>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListTaxesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a tax
 */
export const createTax = (
  taxInput: TaxInput,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.post('/api/v1/taxes', taxInput, options);
};

export const getCreateTaxMutationOptions = <
  TError = AxiosError<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTax>>,
    TError,
    { data: TaxInput },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTax>>,
  TError,
  { data: TaxInput },
  TContext
> => {
  const mutationKey = ['createTax'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTax>>,
    { data: TaxInput }
  > = props => {
    const { data } = props ?? {};

    return createTax(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTaxMutationResult = NonNullable<Awaited<ReturnType<typeof createTax>>>;
export type CreateTaxMutationBody = TaxInput;
export type CreateTaxMutationError = AxiosError<void>;

/**
 * @summary Create a tax
 */
export const useCreateTax = <TError = AxiosError<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTax>>,
      TError,
      { data: TaxInput },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createTax>>,
  TError,
  { data: TaxInput },
  TContext
> => {
  const mutationOptions = getCreateTaxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Fetch a tax
 */
export const getTax = (id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> => {
  return axios.default.get(`/api/v1/taxes/${id}`, options);
};

export const getGetTaxQueryKey = (id?: number) => {
  return [`/api/v1/taxes/${id}`] as const;
};

export const getGetTaxQueryOptions = <
  TData = Awaited<ReturnType<typeof getTax>>,
  TError = AxiosError<void>,
>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTax>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTaxQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTax>>> = ({ signal }) =>
    getTax(id, { signal, ...axiosOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTax>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTaxQueryResult = NonNullable<Awaited<ReturnType<typeof getTax>>>;
export type GetTaxQueryError = AxiosError<void>;

export function useGetTax<TData = Awaited<ReturnType<typeof getTax>>, TError = AxiosError<void>>(
  id: number,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTax>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTax>>,
          TError,
          Awaited<ReturnType<typeof getTax>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTax<TData = Awaited<ReturnType<typeof getTax>>, TError = AxiosError<void>>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTax>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTax>>,
          TError,
          Awaited<ReturnType<typeof getTax>>
        >,
        'initialData'
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetTax<TData = Awaited<ReturnType<typeof getTax>>, TError = AxiosError<void>>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTax>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Fetch a tax
 */

export function useGetTax<TData = Awaited<ReturnType<typeof getTax>>, TError = AxiosError<void>>(
  id: number,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTax>>, TError, TData>>;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTaxQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update a tax
 */
export const updateTax = (
  id: number,
  taxInput: TaxInput,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.put(`/api/v1/taxes/${id}`, taxInput, options);
};

export const getUpdateTaxMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTax>>,
    TError,
    { id: number; data: TaxInput },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTax>>,
  TError,
  { id: number; data: TaxInput },
  TContext
> => {
  const mutationKey = ['updateTax'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTax>>,
    { id: number; data: TaxInput }
  > = props => {
    const { id, data } = props ?? {};

    return updateTax(id, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTaxMutationResult = NonNullable<Awaited<ReturnType<typeof updateTax>>>;
export type UpdateTaxMutationBody = TaxInput;
export type UpdateTaxMutationError = AxiosError<unknown>;

/**
 * @summary Update a tax
 */
export const useUpdateTax = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateTax>>,
      TError,
      { id: number; data: TaxInput },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateTax>>,
  TError,
  { id: number; data: TaxInput },
  TContext
> => {
  const mutationOptions = getUpdateTaxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Delete a tax
 */
export const deleteTax = (
  id: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.default.delete(`/api/v1/taxes/${id}`, options);
};

export const getDeleteTaxMutationOptions = <
  TError = AxiosError<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTax>>,
    TError,
    { id: number },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteTax>>, TError, { id: number }, TContext> => {
  const mutationKey = ['deleteTax'];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTax>>,
    { id: number }
  > = props => {
    const { id } = props ?? {};

    return deleteTax(id, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTaxMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTax>>>;

export type DeleteTaxMutationError = AxiosError<unknown>;

/**
 * @summary Delete a tax
 */
export const useDeleteTax = <TError = AxiosError<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteTax>>,
      TError,
      { id: number },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteTax>>, TError, { id: number }, TContext> => {
  const mutationOptions = getDeleteTaxMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
